# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('first_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('last_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('username', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('avatar', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
