# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterpost',
            name='fake',
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='tweet_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
