# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20180115_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterbot',
            name='happiness',
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='emotion',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
