# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20180512_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='tweet_id',
            field=models.IntegerField(null=True),
        ),
    ]
