# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20180206_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterbot',
            name='pool_owner',
        ),
        migrations.AddField(
            model_name='twitterconversation',
            name='name',
            field=models.CharField(default=b'PLACEHOLDER', null=True),
        ),
        migrations.AlterField(
            model_name='twitterconversation',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='bots.TwitterBot'),
        ),
        migrations.AlterField(
            model_name='twitterconversation',
            name='partner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.TwitterBot'),
        ),
    ]
