# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-07 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20180527_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpost',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
    ]
